### PR TITLE
Feature/enhancements

### PR DESCRIPTION
**Pull request by muraliti**
Initial commit for the sitecore override.

### CODE REVIEW

**Comment by marto83** [comment]
@neilduncan Have a look at this. In the end we didn't split the configuration. It was getting a bit tricky. 
So we added a SitecoreOverride provider and now we go through the providers to find the best value. 

I will also go over it to test for performance implications especially if you resolve a feature multiple times in a request.

**Comment by neilduncan** [comment]
Will do. I'm on imminent baby alert, so it won't be for a couple of weeks!

If you want to get it merged before that, hit up @dannyc02.

**Comment by neilduncan** [comment]
Merged. Finally.

Nice one guys.

**Comment by neilduncan** [comment]
Oh - one thing... Can someone provide a Sitecore Package containing `/sitecore/content/Settings/FeatureToggles` and whatever templates are needed?

@marto83?

**Comment by muraliti** [comment]
Hi Neil, 

Sorry for the late reply.

Attached a screenshot of the template..Just needs a Name/Enabled property.
image

Need to create items out of this template that matches the Feature Name defined in the Aqueduct config file. 
image

Thanks.

**Pull request merged**
